-- MySQL Script generated by MySQL Workbench
-- Sat Sep 27 18:55:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Grados_Academicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grados_Academicos` (
  `idGrados_Academicos` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idGrados_Academicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido_paterno` VARCHAR(100) NOT NULL,
  `apellido_materno` VARCHAR(100) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `escuela` VARCHAR(255) NOT NULL,
  `idGrado_Academico` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuarios_Grados_Academicos1_idx` (`idGrado_Academico` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Grados_Academicos1`
    FOREIGN KEY (`idGrado_Academico`)
    REFERENCES `mydb`.`Grados_Academicos` (`idGrados_Academicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios_Credenciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios_Credenciales` (
  `Usuario_idUsuario` INT NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`),
  INDEX `fk_Usuario_Credenciales_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Credenciales_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apuntes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Apuntes` (
  `idApuntes` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `ruta_archivo` VARCHAR(255) NOT NULL,
  `idUsuario` INT NOT NULL,
  `fecha_subida` DATE NOT NULL,
  PRIMARY KEY (`idApuntes`),
  INDEX `fk_Apuntes_Usuarios1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Apuntes_Usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materias` (
  `idmaterias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idmaterias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `idcomentarios` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `fecha_comentario` DATE NOT NULL,
  `idUsuario` INT NOT NULL,
  `idApunte` INT NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_Usuarios1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_comentarios_Apuntes1_idx` (`idApunte` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_Usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_Apuntes1`
    FOREIGN KEY (`idApunte`)
    REFERENCES `mydb`.`Apuntes` (`idApuntes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Puntuaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Puntuaciones` (
  `idPuntuaciones` INT NOT NULL AUTO_INCREMENT,
  `puntuacion` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idApunte` INT NOT NULL,
  PRIMARY KEY (`idPuntuaciones`),
  INDEX `fk_Puntuaciones_Usuarios1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Puntuaciones_Apuntes1_idx` (`idApunte` ASC) VISIBLE,
  CONSTRAINT `fk_Puntuaciones_Usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Puntuaciones_Apuntes1`
    FOREIGN KEY (`idApunte`)
    REFERENCES `mydb`.`Apuntes` (`idApuntes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apuntes_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Apuntes_materias` (
  `idApuntes_materias` INT NOT NULL AUTO_INCREMENT,
  `idmaterias` INT NOT NULL,
  `idApuntes` INT NOT NULL,
  PRIMARY KEY (`idApuntes_materias`),
  INDEX `fk_Apuntes_materias_materias1_idx` (`idmaterias` ASC) VISIBLE,
  INDEX `fk_Apuntes_materias_Apuntes1_idx` (`idApuntes` ASC) VISIBLE,
  CONSTRAINT `fk_Apuntes_materias_materias1`
    FOREIGN KEY (`idmaterias`)
    REFERENCES `mydb`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apuntes_materias_Apuntes1`
    FOREIGN KEY (`idApuntes`)
    REFERENCES `mydb`.`Apuntes` (`idApuntes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
